### ISSUE TITLE
Text is unselected on hide

### ISSUE THREAD

**Issue by monte-monte** [amezin/gnome-shell-extension-ddterm#101]
So I select some text in the terminal to paste it with middle mouse button to another application > hide the terminal with hotkey > press middle button > nothing happens. After showing terminal window with a hotkey the text appears to be unselected on hide. This is very annoying because after years of using middle button to paste text it became a muscle memory, so losing this functionality have negative effect on the productivity. Can it be fixed?

**Comment by amezin** [comment]
Unfortunately, this is the behavior implemented in VTE library, and I have no control over it. And a fix is unlikely to be accepted by VTE devs, because it's not necessary for GNOME Terminal.

**Comment by amezin** [comment]
Hm, maybe I blame VTE too much. This issue seems to be a consequence of calling `.unrealize()`  when hiding the window (which is itself a workaround for another issue)
