### ISSUE TITLE
Close tab button is "cut" when hovering

### ISSUE THREAD

**Issue by musiclover382** [amezin/gnome-shell-extension-ddterm#105]
Hey, thank you so much for this extension!

For some reason the close tab button has this weird look where the right part of the close tab button is "cut"

![Schermata del 2021-12-15 17-42-03](https://user-images.githubusercontent.com/95233098/146227968-f7fce32b-6c13-4982-85ee-2d9d114a1cba.png)

I get this issue on arch w gnome 41, fedora 35 and manjaro w gnome 40, both wayland and xorg. My screen resolution is 1366x768 but this also happens on other external displays.

**Comment by amezin** [comment]
Yep, known issue, and seems to be theme-dependent. For example, Arc theme (that I use) has no button border (for flat buttons). I wonder if there is a way to get the necessary margins/padding from the theme
