### ISSUE TITLE
Issues with ZSH prompt

### ISSUE THREAD

**Issue by mjnaderi** [amezin/gnome-shell-extension-ddterm#109]
I've set window size to 100% and tabs are on left side.
When I toggle the terminal window multiple times, my shell prompt has strange behavior.

This is my normal shell prompt:

![image](https://user-images.githubusercontent.com/2115303/147456562-35348b0f-6608-41e0-976c-d45ed339d845.png)

After 10 or 20 toggles (without pressing any other key), it turns into something like this:

![image](https://user-images.githubusercontent.com/2115303/147456895-72fa13bd-e7f4-439d-b5c3-b843f2644221.png)

Or this (when tabs are at bottom):

![image](https://user-images.githubusercontent.com/2115303/147457143-d3d3cff5-5dd2-4553-ba47-604546a99dd5.png)

My shell is ZSH and my prompt is https://github.com/romkatv/powerlevel10k. I have similar issue with https://github.com/sindresorhus/pure prompt.

The problem goes away when I change window size to anything except 100% (e.g. 99%).

I tracked the issue to 1cd42a6454d87e49c5cae6c5770909a3b698d574. Before this commit everything is OK.

**Comment by mjnaderi** [comment]
p.s. I'm using Wayland.

**Comment by amezin** [comment]
Could you try this branch https://github.com/amezin/gnome-shell-extension-ddterm/tree/issue-109-workaround ?

**Comment by mjnaderi** [comment]
The work-around has fixed the issue. @amezin thanks.
