### ISSUE TITLE
Tab title customization

### ISSUE THREAD

**Issue by amezin** [amezin/gnome-shell-extension-ddterm#11]
Currently, terminal's 'window-title' is used as tab title.

There are other properties available:
- `icon-title`
- `current-directory-uri`
- `current-file-uri`
- `current-container-name`
- `current-container-runtime`

Would be nice if tab title was configurable using some kind of template language (also, `use-markup` could be enabled for labels)

**Comment by somepaulo** [comment]
Also, a plain text option could be made available in the front-end (say, by right clicking on a tab). I manage several servers and sometimes the username and machine name are the same on different IPs, so being able to rename the tabs as needed would be very helpful.
