### ISSUE TITLE
toggling ddterm doesn't focus into it automatically?

### ISSUE THREAD

**Issue by RJ68** [amezin/gnome-shell-extension-ddterm#115]
Os - Manjaro Gnome
Gnome - 41.3
when i press the the keyboard shortcut or press on the panel icon, it shows the  terminal but doesn't focus into it
is this how its supposed to work or is there something wrong on my end?
can we not have a shortcut which shows the terminal and directly focus into it and also hides the terminal

**Comment by mrjbee** [comment]
Just in case.... got same issue, spend quite time.... solution was to install "steal my focus" extension (just update version if it saying not compatible)

**Comment by nattyebola** [comment]
I don't know why this issue was closed, but I still have the problem.

GNOME Shell 45.0
ddterm 50

**Comment by amezin** [comment]
@nattyebola Please open a new issue, using the bug report form: https://github.com/ddterm/gnome-shell-extension-ddterm/issues/new/choose
