### ISSUE TITLE
Allow us to disable the "Russia-Ukraine War" banner

### ISSUE THREAD

**Issue by PHLAK** [amezin/gnome-shell-extension-ddterm#118]
I understand this is a world-wide topic right now and wish the best for the Ukrainian people. However, I do not want to have this popping up every time I open a new terminal tab. Please allow us to disable this.

**Comment by k3tan172** [comment]
I second this

**Comment by mlalla** [comment]
I second this at well. In the meantime, someone posted a workaround on extensions.gnome.org: You have to comment out line 296 in the appwindow.js file inside the extension folder. (The line in question directly contains the message so should be easy to identify).

**Comment by PHLAK** [comment]
Thank you!
