### ISSUE TITLE
ConnectionSet is not a constructor on gnome 42

### ISSUE THREAD

**Issue by guilhem** [amezin/gnome-shell-extension-ddterm#119]
In an ubuntu jammy 22.04 beta with Gnome 42 + wayland.
Extension version 28 fail with:
```
ConnectionSet is not a constructor
```

May be related to GJS update to 1.71.1

**Comment by amezin** [comment]
There is a merge request on gitlab https://gitlab.com/amezin/gnome-shell-extension-ddterm/-/merge_requests/1
Does it fix ddterm on GNOME v42 for you?

**Comment by libanp** [comment]
The merge request fixes this error on gnome 42 for me

**Comment by amezin** [comment]
Fixed in https://github.com/amezin/gnome-shell-extension-ddterm/commit/78ecbb6e54bd532439389187a532225d5c639871
