### ISSUE TITLE
New tab button in dark theme barely visible

### ISSUE THREAD

**Issue by somepaulo** [amezin/gnome-shell-extension-ddterm#15]
When using dark theme, the '+' icon in the 'New tab' button is barely visible. It should be white(er) and maybe Gnome blue on hover.
![Screenshot](https://user-images.githubusercontent.com/15643750/97930226-ef6ccd00-1d7b-11eb-8c45-300a0a887df3.png)

**Comment by amezin** [comment]
Hm. For me, with default Gtk theme & default icon theme, the button looks like this:

![Screenshot from 2020-11-03 08-27-46](https://user-images.githubusercontent.com/1273397/97943827-c6196480-1dae-11eb-85c5-0cd991ebb89d.png)

What themes are you using?

**Comment by somepaulo** [comment]
I'm using Adwaita with Papirus icons.
Tried switching to Adwaita icons and got the same blue 'plus' icon as the one in your screenshot. Then switched to Papirus Dark and got a white 'plus' in ddterm.
I guess it's due to me using the light variant of Adwaita for most windows with some exceptions like Gedit and Gnome Terminal. However, these two seem to also call in Papirus Dark icons since they're quite white with good contrast.
So unless there is a way to tell GS to load up the dark version of an icon set (if it exists) when using a dark theme variant, there's not much that can be done on your side.

**Comment by amezin** [comment]
I also use light theme for almost everything.

Try opening the terminal, right-click, "Preferences", change "Theme variant" to "Light" and then to "Dark" again. Does it fix the issue?

Also you could try to install the extension from [issue-15](https://github.com/amezin/gnome-shell-extension-ddterm/tree/issue-15) branch (after installing the extension from branch, just close all terminal tabs, and then press "toggle" hotkey - the app will restart). I changed it to set the theme variant earlier - if it's a bug in Gtk, maybe this workaround will fix it.

**Comment by somepaulo** [comment]
Switching theme variants through settings doesn't do it.
I'll try the issue-15 branch tomorrow.

**Comment by somepaulo** [comment]
Tried the issue-15. No luck.
![new tab](https://user-images.githubusercontent.com/15643750/98397747-dc564780-2070-11eb-9362-f08774a6eeda.gif)
I also noticed that the 'close tab' icon has more contrast and does get white on hover:
![closetab](https://user-images.githubusercontent.com/15643750/98397786-ec6e2700-2070-11eb-8eec-ede1f9eeb2c0.gif)
The Drop Down Terminal X uses different icons, and they are always white with no hover effect:
![ddtx](https://user-images.githubusercontent.com/15643750/98383446-8b892380-205d-11eb-8ac8-305cc6529f36.png)
Gedit uses yet another icon, which seems specifically a 'new tab' one:
![gedit](https://user-images.githubusercontent.com/15643750/98383593-bbd0c200-205d-11eb-8130-727f97c8f5cb.png)
Here's what it looks like in Adwaita icon theme:
![gedit adwaita](https://user-images.githubusercontent.com/15643750/98384433-d192b700-205e-11eb-89ee-e2bfd0f2f71a.png)
So my guess is maybe using this 'new tab' icon would do the trick for all icon themes?

**Comment by somepaulo** [comment]
I can confirm that the icon is now looking fine with the latest commits in master, both with Papirus and Adwaita. The icon is white, and the button itself gets a proper highlight on hover.
Thank you!
