### ISSUE TITLE
[Feature request] Use actual drop down / slide up animation

### ISSUE THREAD

**Issue by somepaulo** [amezin/gnome-shell-extension-ddterm#16]
Currently, opening and closing ddterm uses standard GS open/close animations - fade-in&expand-from-center on open and fade-out&shrink-to-center on close. It would be nice if the animation would actually have the terminal window slide down from the top on open and then slide back up on close. Drop Down Terminal extension manages to do this somehow, so their code could give you a hint on how to achieve this if/when you decide to implement this.
This is on X, btw. Haven't tried it on Wayland.

**Comment by amezin** [comment]
I'm not sure I want this feature. It'll probably involve some hacks (fragile) to prevent Mutter's default animations. But IMO it doesn't improve usability at all so not worth it.

**Comment by somepaulo** [comment]
It definitely does not impact usability in any way. It's just an aesthetic thing. Besides it goes with the extension name - drop down, not scale in terminal.

I'm no JS expert, so I can't say whether its a case of hacking or just using what's available in GS already. I had a look at the code of Drop Down Terminal X (it slides down and back up) and found only a few lines of code related to animation. One block handles implementing the animation speed defined in the extension's settings, so it's irrelevant for the functionality itself unless these animation time settings get implemented in the extension options. Other than that, here's all that seems to be related to animations in that extension:
```javascript
const TRANSITION = {
  EASE_OUT: Symbol('transition'), 
  EASE_IN: Symbol('transition')
}

// constants
const ANIMATION_CONFLICT_EXTENSION_UUIDS = [
  'window-open-animation-rotate-in@mengzhuo.org',
  'window-open-animation-slide-in@mengzhuo.org',
  'window-open-animation-scale-in@mengzhuo.org'
]
```
```javascript
// animation setup
this._display = global.screen ? global.screen.get_display() : global.display
this._windowCreatedHandlerId = this._display.connect('window-created', Lang.bind(this, this._windowCreated))
this._actorMappedHandlerId = global.window_manager.connect('map', Lang.bind(this, this._windowMapped))
```
```javascript
this._ease(this._windowActor, targetX, targetY, animationTime, TRANSITION.EASE_IN, {
  opacity: 0,
  onUpdate: () => this._updateClip(),
  onComplete: () => {
    Main.ctrlAltTabManager.removeGroup(this._windowActor)
    this._windowActor = null
    this._busProxy.ToggleRemote()
  }
})
```
```javascript
_ease (actor, x, y, time, transitionMode, { scaleY, opacity, onComplete, onUpdate}) {
  if (Tweener) {
    const transition = transitionMode === TRANSITION.EASE_IN ? 'easeInExpo' : 'easeOutExpo'
    Tweener.addTween(actor, { x, y, time, transition, onComplete, onUpdate, scale_y: scaleY })
  } else {
    const transition = transitionMode === TRANSITION.EASE_IN ? Clutter.AnimationMode.EASE_IN_QUAD : Clutter.AnimationMode.EASE_OUT_QUAD
    actor.ease({ x, y, transition, opacity, onUpdate, onComplete, scale_y: scaleY })
  }
}
```
```javascript
// animate the opening sequence if applicable
if (this._shouldAnimateWindow() && this._openingAnimationTimeMillis > 0) {
  // FIXME: we should reset those on monitors-changed
  //
  // to avoid an animation glitch where we could briefly see the window at its target position before the animation starts,
  // we initialize the animation in this thread -at actor mapping time- so the window is not yet visible and can be placed out of the screen
  //
  // Update: starting from mutter 3.7.90, there is no animation at all if the actor is not displayed (out of the screen) at map time.
  //         This might be a side-effect of the new frame synchronization changes. To work around that until I figure out a better fix,
  //         schedule the whole animation in the next frame (idle_add) and make the actor transparent until the animation starts
  //         (to avoid the brief window appearance which is the original issue).
  //
  //         Tonic: I added a workaround by making sure at least one pixel is on the screen.
  this._windowActor.opacity = 0

  Mainloop.idle_add(() => {
    const terminalPosition = this._settings.get_enum(TERMINAL_POSITION_SETTING_KEY)
    this._windowActor.opacity = 255

    // Workaround animation bug by making sure the window is partially on screen.
    const workaround = 1
    switch (terminalPosition) {
      case LEFT_EDGE:
        this._windowActor.set_position(this._windowX - this._windowActor.width + workaround, this._windowY)
        break
      case RIGHT_EDGE:
        this._windowActor.set_position(this._windowX + this._windowActor.width - workaround, this._windowY)
        break
      case BOTTOM_EDGE:
        this._windowActor.set_position(this._windowX, this._windowY + this._windowActor.height - workaround)
        break
      default:
      case TOP_EDGE:
        this._windowActor.set_position(this._windowX, this._windowY - this._windowActor.height + workaround)
        break
    }

    const time = this._openingAnimationTimeMillis / 1000.0
    this._ease(this._windowActor, this._windowX, this._windowY, time, TRANSITION.EASE_OUT, {
      scaleY: 1.0,
      opacity: 255,
      onUpdate: () => this._updateClip(),
      onComplete: () => completeOpening()
    })      
  })
} else {
  completeOpening()
}
```
and
```javascript
_shouldAnimateWindow () {
  if (!this._animationEnabled || !Main.wm._shouldAnimate()) {
    return false
  }

  if (Main.extensionManager) {
    // since gnome 3.36
    for (const extUUID in Main.extensionManager.getUuids()) {
      const ext = Main.extensionManager.lookup(extUUID)
      if (ext && ANIMATION_CONFLICT_EXTENSION_UUIDS.indexOf(ext.uuid) >= 0 && ext.state == ExtensionSystem.ExtensionState.ENABLED) {
        return false
      }
    }  
  } else {
    // for legacy versions 
    for (const ext in ExtensionUtils.extensions) {
      if (ANIMATION_CONFLICT_EXTENSION_UUIDS.indexOf(ext.uuid) >= 0 && ext.state == ExtensionSystem.ExtensionState.ENABLED) {
        return false
      }
    }
  }
```
Please have a look at this code. Maybe it's not hacking GS and hopefully you could implement it in your extension when you get some time for it even though it's not a showstopper and not essential.

Thank you for your extension. It's my new favourite even with these minor visual nags, and it beats the other ones fair and square.

**Comment by amezin** [comment]
It seems that there is an appropriate function that cancels default animations: [Main.wm.skipNextEffect()](https://gitlab.gnome.org/GNOME/gnome-shell/-/blob/gnome-3-36/js/ui/windowManager.js#L1105)
So, at least, no hacks here. I think it's possible to implement, though still not a high priority

**Comment by somepaulo** [comment]
Good to know no hacks are needed.
Hope you'll find some time to implement this in the future.
Definitely not a high priority.
Thank you!

**Comment by amezin** [comment]
Unfortunately, `Main.wm.skipNextEffect()` will make Shell's js code call `completed_map()` immediately: https://gitlab.gnome.org/GNOME/gnome-shell/-/blob/gnome-3-36/js/ui/windowManager.js#L1470

And `completed_map()` docs say: The plugin must call this when it has completed a window map effect.
https://gjs-docs.gnome.org/shell01~0.1_api/shell.wm#method-completed_map

So the only solution seems to be monkey-patching private functions in `windowManager.js`. A fragile hack that I don't want to do. At least for a feature that doesn't actually add anything significant

Also I remember that drop-down-terminal-x has some issues with focus during animation (when I start typing immediately after pressing the toggle hotkey, key presses go into previously active window, not the terminal)

**Comment by somepaulo** [comment]
Shame.
I hope some day this will be possible natively or through other plugins like the Compiz effects ones.

**Comment by somepaulo** [comment]
Maybe the Animation Tweaks extension https://extensions.gnome.org/extension/1680/animation-tweaks/ & https://github.com/Selenium-H/Animation-Tweaks could give a hint in the right direction.

**Comment by amezin** [comment]
I've figured how to do it, will be available in the next release
