### ISSUE TITLE
Window Randomly Presents in the Middle of the Screen

### ISSUE THREAD

**Issue by moore-bryan** [amezin/gnome-shell-extension-ddterm#19]
As you can see from the attached screenshot, ddterm will randomly present in the middle of the screen rather than the top. Any ideas? Happy to provide logs if directed to where to find them...
![Screenshot-20201130095453-1919x1044](https://user-images.githubusercontent.com/8169342/100625078-1faf7900-32f2-11eb-81eb-dfc09517b4ad.png)

**Comment by amezin** [comment]
Does this happen in Wayland or XOrg session? If Wayland, is "Force X11 GDK backend" enabled in Preferences?

**Comment by amezin** [comment]
> ddterm will randomly present in the middle of the screen rather than the top

So it happens only sometimes, not every time? Also, what version of GNOME Shell do you have installed?

**Comment by moore-bryan** [comment]
Wayland on the latest Manjaro with GNOME 38.8.2 and the 5.8.18 kernel.

I had it happen once yesterday and once today, so I've check the "Force X11 GDK Backend" option and logged out/in and things are fixed for now; I'll report back if they change.

Thanks for the help @amezin. Any chance you can share what the backend option does?

**Comment by amezin** [comment]
But the latest released version of gnome shell is 3.38.1.. https://gitlab.gnome.org/GNOME/gnome-shell/-/tags

**Comment by moore-bryan** [comment]
And yet... ;-)
![Screenshot-20201130132458-992x910](https://user-images.githubusercontent.com/8169342/100648842-8a22e200-330f-11eb-95d2-7e9131e4bd5c.png)

**Comment by amezin** [comment]
@moore-bryan 

> I had it happen once yesterday and once today, so I've check the "Force X11 GDK Backend" option and logged out/in and things are fixed for now; I'll report back if they change.

Well, then you can't say "it's fixed" for sure - at least until you test it for a few days.

> Any chance you can share what the backend option does?

"Force X11 GDK backend (XWayland)" option forces the application to use X11 backend, even in Wayland session - so it runs under XWayland. This triggers different code paths in both GTK and Mutter. But my goal is to make the application work perfectly on native Wayland - so enabling XWayland option isn't a solution that I like.

In https://github.com/amezin/gnome-shell-extension-ddterm/commit/2aec9879f6cf77d0253581b7683a578f3b31a8bd I added another attempt to move and resize the window into correct location (`shown` signal is emitted on Wayland only, so it should only have effect on Wayland). Could you test the code from the current `master` branch (with XWayland option disabled)?

**Comment by moore-bryan** [comment]
I completely agree, @amezin, about the fix being prospective.

I just removed the "old" one and git cloned the master, so I'll let you know if there are any issues. Thank you for your quick response to what I can only imagine is a labor of love.

**Comment by amezin** [comment]
:((

Currently I'm out of ideas

**Comment by moore-bryan** [comment]
Me, too... Checking "Force X11 GDK Backend" _seems_ to work, but I agree that's not a great option...

**Comment by amezin** [comment]
Does it happen when you open the terminal for the first time after login/after you've closed all tabs? (the application exits when you close the last tab, and starts only when you try to toggle the terminal)

Next time when it happens, please run `journalctl --user -n 100 > log.txt` and attach that `log.txt` here. Maybe there will be an error message somewhere

**Comment by amezin** [comment]
Hm.. Dual-monitor configuration on X11 is now broken in a similar way. And I remember that it worked previously

**Comment by amezin** [comment]
I've found a solution for the issue on dual-monitor X11 - maybe it will also fix the issue you're observing. Please retest the current `master` branch

**Comment by amezin** [comment]
@moore-bryan Does this bug still occur with the current version (v5, it's on https://extensions.gnome.org/extension/3780/ddterm/ now)?

**Comment by moore-bryan** [comment]
Sorry for taking so long to respond, but I needed to completely
reinstall my os; long story.

So far, version 5 doesn't seem to have the same bug. If I may impose,
what was it?

**Comment by amezin** [comment]
> So far, version 5 doesn't seem to have the same bug. If I may impose, what was it?

Honestly, I don't understand Mutter's window placement code. Previously, I thought that passing `user_op=true` to `Meta.Window.move_resize_frame()` will ensure that the window will be moved to the correct position (move/resize operation won't be ignored). But it turned out to be exactly the opposite.

**Comment by moore-bryan** [comment]
I don't think you're the only one... Mutter's placement code is a mess.

Thanks for a great extension and your work on getting it to properly
function!
--
*B.Moore*

**Comment by moore-bryan** [comment]
Just wanted to reach back out and let you know this issue persists in
Fedora 34...
--
*B.Moore*

**Comment by amezin** [comment]
Can't reproduce it on Fedora 34 VM. On Arch (with Gnome 40) it doesn't happen.

Are you sure you're using the latest version (v12) of the extension?

**Comment by moore-bryan** [comment]
I can confirm I'm on version 12 of the extension, but can't confirm if
the intermittent problem was on the previous version; I've reset the
preferences to not use XWayland and I'll report back if the issue
arises again.

Thanks for your development of this and your quick responses!

-----Original Message-----
From: Aleksandr Mezin ***@***.***>
Reply-To: amezin/gnome-shell-extension-ddterm
***@***.***>
To: amezin/gnome-shell-extension-ddterm
***@***.***>
Cc: Bryan Moore ***@***.***>, Mention
***@***.***>
Subject: Re: [amezin/gnome-shell-extension-ddterm] Window Randomly
Presents in the Middle of the Screen (#19)
Date: Thu, 01 Apr 2021 20:55:59 -0700

Can't reproduce it on Fedora 34 VM. On Arch (with Gnome 40) it doesn't
happen.
Are you sure you're using the latest version (v12) of the extension?
