### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by amezin** [amezin/gnome-shell-extension-ddterm#20]
Got a bug report by email:

> Hello, I'm not completely sure if the problem comes from ddterm, but it seems that there is a memory leak in this extension. It is never killed by oom-killer because gnome is whitelisted. Tested on F33, it consumes my RAM and my SWAP very quickly, so a lot of useful process such as firefox, element, discord ... are killed by eatryoom. Removing the extension  solved the problem.

> yes, it happens when only ddterm is enabled, on a fresh fedora 33 installation.

> The observed behaviour was an increase in RAM each time the toggle key was pressed, which was never released and saturate SWAP + RAM quickly. The problem seems solved when the extension if disabled.

[memleak.txt](https://github.com/amezin/gnome-shell-extension-ddterm/files/5633275/memleak.txt)

**Comment by amezin** [comment]
I can't reproduce the issue on a Fedora 33 VM though

**Comment by sowrensen** [comment]
Can confirm. Gnome 38 on Manjaro. Each time I pressed the shortcut key, the memory usage increased by 1%-2%.

**Comment by amezin** [comment]
@sowrensen Which application do you use for monitoring?

Do you have any other extensions enabled? (if you disable other extensions for testing - please restart the shell, otherwise there's a chance that some extension didn't clean up after itself properly)

I see that memory usage grows by a few kb every time I toggle the terminal, but then at some point the shell runs GC, and memory usage drops by a few megabytes - to the original value when I started testing.

**Comment by sowrensen** [comment]
> I see that memory usage grows by a few kb every time I toggle the terminal, but then at some point the shell runs GC, and memory usage drops by a few megabytes - to the original value when I started testing.

Yes, you are right. The memory usage returns to the usual value after sometime. I didn't notice it earlier, sorry for that. And I didn't disable other extensions. Usually the usage is around 22-24% when no application is running. I have monitored the behavior using system monitor and a desktop widget, "The Circles".

**Comment by Roel69** [comment]
I can confirm this issue in a Xorg session. RAM and SWAP memory filled to the point my system (Manjaro GNOME 3.38.2) was unusable. Switching off or removing the extension solved the problem. In a Wayland session I have no problem at all.

**Comment by amezin** [comment]
@Roel69 thank you, yes, I can reproduce the issue in Xorg session. Still no idea why it happens though

**Comment by amezin** [comment]
I think I've figured out what happens. The leak is in the application, not shell extension:
`Gtk.Widget.draw` signal handler, when implemented in JS, leaks GPU memory on X11.

Well, it isn't even a 'leak'.. it's just GC not being triggered (because RAM usage - or at least RSS - is small). Every time `draw` handler is called, a reference to a new cairo context is passed into it. And that cairo context is then not destroyed/not released for a long time.

**Comment by amezin** [comment]
https://gitlab.gnome.org/GNOME/gjs/-/issues/370
