### ISSUE TITLE
100% window height is actually 1 pixel less

### ISSUE THREAD

**Issue by somepaulo** [amezin/gnome-shell-extension-ddterm#21]
I have ddterm with `Window height` option set to 1.00 (the maximum available value) by default, but since the last update it stopped covering the full height of the screen, leaving one pixel uncovered at the bottom.

![Screenshot](https://user-images.githubusercontent.com/15643750/104470698-0d03b180-55cb-11eb-8549-9796058ab436.png)

If I enable the `Resizeable window` option I can drag it to full height, but it restores itself to 100%-1px on next toggle.
Tried setting `Window height` to 1.01 through dconf Editor, but that messes things up.
Please check.

**Comment by amezin** [comment]
It's intentional. If window's initial height is exactly 100%, unmaximizing it (necessary for resizing) will also move it. Probably the 1px offset can be removed when the window isn't resizable... But I'd prefer to keep things simple and always subtract that 1px.

**Comment by somepaulo** [comment]
I might be the only one out there who uses all dropdown terminals always at 100% height, but still, this pixel, especially when it's white, is extremely annoying. Can you at least point me to the bit of code that does it so I can disable this pixel offset and keep a personal fork for myself, please? А то реально бесит, как битая матрица с полосой неработающих пикселей.
