### ISSUE TITLE
Port to Gnome Shell 40

### ISSUE THREAD

**Issue by snaggen** [amezin/gnome-shell-extension-ddterm#24]
As explained in https://blogs.gnome.org/shell-dev/2021/03/12/gnome-40-your-extension/ , all extensions needs to be ported over to Gtk4 to work with Gnome Shell 40. 
So, this is just a friendly reminder since Gnome Shell 40 is coming soon.

**Comment by amezin** [comment]
Fixed in https://github.com/amezin/gnome-shell-extension-ddterm/releases/tag/v10
