### ISSUE TITLE
Wrong placement of window on empty secondary screen

### ISSUE THREAD

**Issue by snaggen** [amezin/gnome-shell-extension-ddterm#28]
I have a laptop and a external monitor, the top of my laptop monitor is configured just above the middle of the secondary screen.  I open some programs on my laptop, the ddterm works as expected on that. If I then move my mouse and click on the background on the empty external screen and show ddterm, that will not be placed on top, but on the external screen (as expected) but with the top position from the laptop screen, which means just above middle of the external screen. 
If I have any program running on the external screen (even on another virtual desktop) it will be displayed on top as it should. So, it is just when there is nothing else running on the external screen. 
Here is a screenshot, I have a full screen terminal on my laptop and nothing on my external screen. 
![Skärmbild från 2021-03-26 09-21-31](https://user-images.githubusercontent.com/6420639/112603027-b5789200-8e14-11eb-8193-2de3da53b4f0.png)

**Comment by amezin** [comment]
- What version of GNOME Shell are you running?
- What distro?
- Xorg or Wayland session?
- If Wayland, does anything change if you enable `Preferences`->`Window`->`Force X11 GDK Backend` (you'll have to close all tabs for this option to take effect)?

**Comment by snaggen** [comment]
Sorry for leaving out that info.
I run Fedora 34 Beta, with Gnome 40 and a Wayland Session. If I Force X11 it behaves correct, so it is just for the Wayland backend it seems.

**Comment by amezin** [comment]
Yes, I can reproduce it now.

Seems to happen only if there is a maximized window on the primary monitor, and nothing on another one

**Comment by amezin** [comment]
Fix will be included in the next version. Or you can install from git repository: https://github.com/amezin/gnome-shell-extension-ddterm/blob/master/docs/INSTALL.md
