### ISSUE TITLE
Keyboard shortcut for Maximizing Terminal

### ISSUE THREAD

**Issue by henrj** [amezin/gnome-shell-extension-ddterm#29]
First of all thanks for this amazing extension, it feels so integrated with the gnome-shell and its a pleasure to use.

The only thing I miss coming from Guake its the feature where a keyboard shortcut toggles the terminal window to fullscreen and back to the original size.

In guake the default its F11.

Was looking at the code to see how can I contribute or at least try to add this feature with no success.

Where should I start looking?

**Comment by amezin** [comment]
1. Add `maximize` `Gio.Action` to `appwindow.js`: https://github.com/amezin/gnome-shell-extension-ddterm/blob/c062f0dc2289c8695c23d822066230d1dfcc2566/appwindow.js#L55-L66
2. Add keyboard shortcut to settings schema: https://github.com/amezin/gnome-shell-extension-ddterm/blob/c062f0dc2289c8695c23d822066230d1dfcc2566/schemas/com.github.amezin.ddterm.gschema.xml#L246-L330
3. Add keyboard shortcut to shortcut table in `prefs.ui`: https://github.com/amezin/gnome-shell-extension-ddterm/blob/c062f0dc2289c8695c23d822066230d1dfcc2566/glade/prefs.ui#L301-L464
4. Connect the shortcut to the action in `application.js`: https://github.com/amezin/gnome-shell-extension-ddterm/blob/c062f0dc2289c8695c23d822066230d1dfcc2566/application.js#L122-L137

**Comment by henrj** [comment]
**Thanks** for the detailed reply... Looking into it
