### ISSUE TITLE
Feature Request: Width and Alignment Settings.

### ISSUE THREAD

**Issue by uroybd** [amezin/gnome-shell-extension-ddterm#31]
Along with height, a width and alignment (left, right, top, bottom) settings will be very helpful. For example, I like my terminal full-height with 40% width in the right of my screen. These settings will allow a wider range of users to use this tool more efficiently.

**Comment by amezin** [comment]
Most likely I won't work on this feature myself, as it's not something I'll use.

If somebody would make a pull request implementing this (and not breaking anything else) - I'll merge it.

**Comment by uroybd** [comment]
#32

I never developed extensions before. Hopefully didn't messed it up.

**Comment by uroybd** [comment]
> Got a problem in alignment though. It works fine X11, but in Wayland even if I select right alignment it shows in left on toggling again.

This can be avoided if I set 'Force X11 GDK backend (XWayland)' to true.

**Comment by amezin** [comment]
> Got a problem in alignment though. It works fine X11, but in Wayland even if I select right alignment it shows in left on toggling again.

That's a problem. One of my primary goals when I started this project was (native) wayland compatibility. So I don't add features that don't work on Wayland. At least currently.

Maybe moving the window to the correct position in response to [Window.position-changed signal](https://gjs-docs.gnome.org/meta7~7_api/meta.window#signal-position-changed) will help

**Comment by uroybd** [comment]
> > Got a problem in alignment though. It works fine X11, but in Wayland even if I select right alignment it shows in left on toggling again.
> 
> That's a problem. One of my primary goals when I started this project was (native) wayland compatibility. So I don't add features that don't work on Wayland. At least currently.
> 
> Maybe moving the window to the correct position in response to [Window.position-changed signal](https://gjs-docs.gnome.org/meta7~7_api/meta.window#signal-position-changed) will help

Seems like connecting `update_window_geometry` with the `position-changed` did the trick! It's working fine now.

**Comment by amezin** [comment]
Won't implement and won't accept pull request, sorry.

This creates too many possible configurations (with half of them looking broken) that need to be tested, too many new things in the preferences dialog (which is already overloaded). And it seems that even you don't need that flexibility (and complexity) yourself.

I'm ok with https://github.com/amezin/gnome-shell-extension-ddterm/issues/35 though

Closed in favor of https://github.com/amezin/gnome-shell-extension-ddterm/issues/35
