### ISSUE TITLE
Hotkeys not available as "Shortcuts"

### ISSUE THREAD

**Issue by corna** [amezin/gnome-shell-extension-ddterm#33]
I'm trying to use the "Favorite key" (F12 without pressing "Fn") as "Toggle terminal" on Lenovo Thinkpad X1 Carbon 8th generation. However, while the "standard" keys are correctly detected, the "hotkeys" are not, while they are instead being correctly detected in the GNOME Keyboard Bindings page.

Is there a way to use them as "shortcuts" in ddterm? Alternatively, is there a command to toggle the visibility of ddterm, so that I can bind that command form the GNOME Keyboard Bindings interface to toggle ddterm?

**Comment by amezin** [comment]
Interesting. If I remember correctly, I copy-pasted the code for keyboard shortcuts table from Gtk documentation or something like that :) I'll look into it

> Alternatively, is there a command to toggle the visibility of ddterm, so that I can bind that command form the GNOME Keyboard Bindings interface to toggle ddterm?

Unfortunately, no. There is a `app.toggle` GAction, that can be triggered from the command line, but it won't work if the application haven't been started yet (the extension starts the application when you try to open it for the first time, not when the shell starts). There was `--toggle` CLI option previously, probably I should restore it.

**Comment by amezin** [comment]
A note for myself: seems that to receive media keys you have to do this https://gitlab.gnome.org/GNOME/gnome-control-center/-/blob/master/panels/keyboard/cc-keyboard-shortcut-editor.c#L201-230 (i. e. `gdk_seat_grab()` with `GDK_SEAT_CAPABILITY_KEYBOARD`)
This should probably be done only for "toggle" shortcut - it's handled by the extension == by the shell. Application will probably need a grab to be able to handle this kind of shortcuts - which is unacceptable.

**Comment by amezin** [comment]
There is now a CLI command to toggle the terminal: https://github.com/amezin/gnome-shell-extension-ddterm#toggle-the-terminal-through-d-bus (only in `master` branch, no release yet).

Also, preferences dialog captures media/fn keys in branch [`toggle-terminal-media-keys`](https://github.com/amezin/gnome-shell-extension-ddterm/tree/toggle-terminal-media-keys). It doesn't work on Gtk 4: so if you open extension preferences on Gnome 40, it won't work. However, it will always work if you right-click on the terminal window and choose "Preferences..." (the app will probably stay on Gtk 3 for a long time).
