### ISSUE TITLE
[FEATURE] Allow terminal to come from the left or right of the screen, not only up top

### ISSUE THREAD

**Issue by Shaltz** [amezin/gnome-shell-extension-ddterm#35]
Hi, 

I really like this extension, coming from DropDownTerminal X, I really appreciate the sturdiness
and the settings available. However, there is one functionality that I miss and which is a must for me, 
it's the ability to bring up the terminal from the left or right of the screen.

do you think it's something doable ??

thanks in advance and keep up the good work ;)

**Comment by amezin** [comment]
See https://github.com/amezin/gnome-shell-extension-ddterm/issues/31
There is a pull request in progress https://github.com/amezin/gnome-shell-extension-ddterm/pull/32

**Comment by amezin** [comment]
Actually, https://github.com/amezin/gnome-shell-extension-ddterm/issues/31 is way too complex. This is looking more reasonable (with resizing only in one dimension and only 4 window positions)
