### ISSUE TITLE
Using a composite shortcut for Toggle Terminal Window

### ISSUE THREAD

**Issue by jonasbb** [amezin/gnome-shell-extension-ddterm#36]
I would like to use `` Ctrl+` `` (key above tab) as a shortcut for "Toggle Terminal Window" but it only seems to allow me to set a single key as the shortcut, meaning it will set the shortcut to `Control L`. Is that an intended limitation? I used Drop Down Terminal X before where this worked.

**Comment by amezin** [comment]
No, it's not intended. I've just tested it, seems to happen on Gtk 4 only.

For now, you could open "Preferences" dialog from the context menu of the terminal - it opens Gtk 3 version of the dialog, you should be able to set shortcut to Ctrl+` there

**Comment by jonasbb** [comment]
Thank you, that works.
Interestingly, the application shortcuts (non-global) do allow composite shortcuts even with the Gtk 4 dialog.
