### ISSUE TITLE
Left-Ctrl backtick as hotkey

### ISSUE THREAD

**Issue by reinouts** [amezin/gnome-shell-extension-ddterm#37]
Hi,

I came here because the dropdown terminal-x extension is no longer supported. 

My issue is that I tried to set the Left Ctrl+` keycombo as the shortcut for ddterm like I had before, but it appears that ddterm only accepts single keys. Can these keycombo's be supported as well please?

**Comment by SaintWacko** [comment]
I just switched over for the same reason, and meta-key shortcuts are definitely supported (I use alt+`). Check your system hotkeys, one of them may be using ctrl+`

**Comment by amezin** [comment]
> My issue is that I tried to set the Left Ctrl+` keycombo as the shortcut for ddterm like I had before, but it appears that ddterm only accepts single keys. Can these keycombo's be supported as well please?

See https://github.com/amezin/gnome-shell-extension-ddterm/issues/36

Fix is in `master` https://github.com/amezin/gnome-shell-extension-ddterm/commit/8f9f4dbee12a04f3319489290254d97015b83922 but not in any release yet

**Comment by reinouts** [comment]
Thank you. The workaround from #36 works!
