### ISSUE TITLE
Feature Request: Change position of tabs

### ISSUE THREAD

**Issue by SaintWacko** [amezin/gnome-shell-extension-ddterm#38]
As one of many people who have switched over from Drop Down Terminal X, I became accustomed to having my tabs vertically on the right side of the terminal. Is this a feature you could add? I feel they make more sense there, especially on wide monitors.

**Comment by amezin** [comment]
Will be available in the next release.

Or you could try installing in-development version from the repository https://github.com/amezin/gnome-shell-extension-ddterm/blob/master/docs/INSTALL.md

**Comment by SaintWacko** [comment]
Ah, excellent! My apologies if I missed that somewhere.
