### ISSUE TITLE
Hide the window rather than close it when pressing window close shortcut.

### ISSUE THREAD

**Issue by LiinXemmon** [amezin/gnome-shell-extension-ddterm#39]
Is there any way to make the window hidden rather than closed when pressing window close shortcut?

**Comment by amezin** [comment]
What exactly do you mean by "hidden rather than closed"? From Gtk's POV, the window is hidden, not closed: https://github.com/amezin/gnome-shell-extension-ddterm/blob/a5058a85dd145c6649bbb0b73ea3dd6a04cc27b9/appwindow.js#L166

**Comment by amezin** [comment]
Fix will be available in the next release.

Or you can install in-development version from the repository https://github.com/amezin/gnome-shell-extension-ddterm/blob/master/docs/INSTALL.md

**Comment by LiinXemmon** [comment]
Thanks for fixing it. I need it because I sometimes close it intuitively using window close shortcut. 

Your extension is awesome and I really like it, especially at the moment you know few extensions supporting gnome 40.😁
