### ISSUE TITLE
missing tray icon

### ISSUE THREAD

**Issue by maxadamo** [amezin/gnome-shell-extension-ddterm#43]
it works if I press F12, but I don't see an option to enable a tray icon.

**Comment by amezin** [comment]
I thought about it myself... Maybe it will be useful for new users - when you don't know the hotkey to show the terminal. But is it really useful after that? Why do you need it?

**Comment by maxadamo** [comment]
I can agree with to you. It's really entirely up to you. Let's say, you may want to investigate, if there is a 20% of users (not me, I'm fine with F12) who'd like to click the tray icon. 
I have asked this question mostly because all the quake-style terminals implement a tray icon.
