### ISSUE TITLE
Feture Request: Disabling Animation

### ISSUE THREAD

**Issue by uroybd** [amezin/gnome-shell-extension-ddterm#50]
Hi,

An option to disabling show/hide animation altogether would be nice. Can it be implemented?

**Comment by amezin** [comment]
I don't know. `Main.wm.skipNextEffect()` should be called before the animation is set up. But `override_[un]map_animation()` are called after Shell's handlers for `global.window_manager.map/destroy`, i. e. default animations are started already. And calling `skipNextEffect()` from other signal handlers won't be reliable - will probably cancel unrelated animations

**Comment by amezin** [comment]
Implemented in https://github.com/amezin/gnome-shell-extension-ddterm/releases/tag/v20
