### ISSUE TITLE
Shortcuts and other Features stop working after some time

### ISSUE THREAD

**Issue by smoebody** [amezin/gnome-shell-extension-ddterm#51]
After some time the shortcut for open/close is not working anymore. I have to kill the `gjs` process for ddterm in order to make it work again. The journal shows the following message:
```
Jun 07 08:38:07 ilng002v98 gnome-shell[5480]: == Stack trace for context 0x5596b84d01c0 ==
Jun 07 08:38:07 ilng002v98 gnome-shell[5480]: #0   5596b868e800 i   /home/smoe/.local/share/gnome-shell/extensions/ddterm@amezin.github.com/application.js:253 (20fdbb89b1f0 @ 750)
Jun 07 08:38:07 ilng002v98 gjs[5480]: The offending signal was draw on Gjs_AppWindow 0x5596b87722a0.
Jun 07 08:38:07 ilng002v98 gjs[5480]: Attempting to call back into JSAPI during the sweeping phase of GC. This is most likely caused by not destroying a Clutter actor or Gtk+ widget with ::destroy signals connected, but can also be caused by using the destroy(), dispose(), or remove() vfuncs. Because it would crash the application, it has been blocked and the JS callback not invoked.
```

Im on Fedora 34 with Gnome 40, using Wayland.

**Comment by amezin** [comment]
I do not have the same issue on Gnome 40 + Wayland on Arch Linux. Weird.
Messages like this can be generated when you kill the application, it doesn't help much. Or does it appear before you kill the application?

**Comment by smoebody** [comment]
Yes, before I kill the app. In this case it was the process with pid 5480 which i had to kill

**Comment by amezin** [comment]
Does it happen if you set background opacity to 100%?

**Comment by amezin** [comment]
Can't reproduce on a Fedora 34 VM (script showing/hiding terminal in a loop for ~1 hour)

**Comment by amezin** [comment]
@smoebody If it still happens, could you upload full session log (i. e. output of `journalctl --user -b`)?

4 lines that you posted aren't enough to figure out what's going on.

**Comment by smoebody** [comment]
@amezin sorry for the long delay.

I cannot reliable reproduce the issue, but from what i see it has something to do with Gnome40/Wayland + Suspend/Awake + Intel UHD 620 Graphics. 
I will ket you know as soon as i can reproduce the issue. 
Thanks for taking interest.

**Comment by amezin** [comment]
@smoebody so, I guess it doesn't happen anymore?

**Comment by smoebody** [comment]
at least i cannot reproduce it reliably. therefore I am fine with closing this issue due to insufficient information.
