### ISSUE TITLE
Add a keyboard shortcut to toggle background opacity

### ISSUE THREAD

**Issue by Henry78** [amezin/gnome-shell-extension-ddterm#52]
I suggest to add a (new) keyboard shortcut to toggle the opacity between configured value and 100%

Motivation: This help me, who likes to be able to view "through" ddterm to write off stuff "below" in situation where the content below makes the term difficult read. In such situation I'd love to hit some key combo to toggle the background 100% opaque.

**Comment by amezin** [comment]
Will be available in v19
