### ISSUE TITLE
Toggle through open tabs

### ISSUE THREAD

**Issue by piotr-jakacki** [amezin/gnome-shell-extension-ddterm#54]
A lot of prominent session managers support toggling through opened tabs (oftentimes default shortcut is ctrl+tab) rather than using a shortcut to go to a specific tab. Could something like this be implemented?

**Comment by amezin** [comment]
Why don't "Switch to Previous Tab"/"Switch to Next Tab" work for you?

**Comment by amezin** [comment]
Now "Switch to Previous/Next Tab" shortcuts will cycle through open tabs, i. e.:

"Switch to Previous Tab" will switch to the last tab if the current one is first.
"Switch to Next Tab" will switch to the first tab if the current one is last.

Will be available in v19.

Other than this, I don't see what could be missing.
