### ISSUE TITLE
"forgets" custom command?

### ISSUE THREAD

**Issue by wpalmer** [amezin/gnome-shell-extension-ddterm#56]
I have found that on occasion, ddterm "forgets" that I have told it to run a custom command.
The custom command itself is still remembered, it just stops running it, instead running a shell.

I have not noticed any pattern which might indicate _why_ this occurs. It seems very strange.

**Comment by amezin** [comment]
Oops. Yes, it seems to be broken. For me it forgets what was selected in "Preferences->Command" every time. Working on a fix

**Comment by amezin** [comment]
Fix is in master branch: https://github.com/amezin/gnome-shell-extension-ddterm/commit/2a1bf8982f5ecf9e2cfbe0526bae0f359aef8fc0 ( https://github.com/amezin/gnome-shell-extension-ddterm/blob/master/docs/INSTALL.md )

Will be available in v19
