### ISSUE TITLE
Mark window type as MetaWindow

### ISSUE THREAD

**Issue by nre-ableton** [amezin/gnome-shell-extension-ddterm#60]
In some tiling window managers (like [pop-shell](https://github.com/pop-os/shell)), ddterm is incorrectly treated as a regular window and tiled amongst other desktop windows when shown. pop-shell has an exception list for applications which should not be tiled, and ddterm [will be added to that list](https://github.com/pop-os/shell/issues/1034#issuecomment-873453811) at some point, but it would be nice if ddterm marked its window as a [MetaWindow](https://developer.gnome.org/meta/stable/MetaWindow.html#MetaWindowType) so that it was handled correctly by such window managers.

Thanks for ddterm, and keep up the good work!

**Comment by amezin** [comment]
Preferences -> Window -> Window type hint (X11 only)

As you can see, it works only on X11 or XWayland, because on Wayland Gtk 3 ignores it. Also, if you change window type hint to anything other than "Normal", window animations will stop working

**Comment by nre-ableton** [comment]
Ah, I hadn't noticed that. Sorry for the noise!
