### ISSUE TITLE
Copy on select feature

### ISSUE THREAD

**Issue by abdulrahman19** [amezin/gnome-shell-extension-ddterm#64]
First of all, I want to thank everyone who works on this awesome extension, but I think this extension missing a critical feature which is `copy on select` to copy any text to the clipboard when select them, it saves a lot of time, please add it!

**Comment by amezin** [comment]
As far as I can tell, the feature is small and simple; somebody with basic Gtk and gjs knowledge could implement it.

**Comment by amezin** [comment]
While working on a search bar, I've just discovered that Vte automatically copies selected text to the "primary" selection and pastes that text on a middle click.

So this is already implemented in Vte, and I see no reason to alter its behavior.

**Comment by alejoar** [comment]
Doesn't work with tmux
