### ISSUE TITLE
Content within preferences panel should scale to size of window

### ISSUE THREAD

**Issue by jacksongoode** [amezin/gnome-shell-extension-ddterm#71]
I've just noticed that some tabs within the preferences remain static while others will align to the left side as the window size increases. Another note here, the minimum size of the window is quite large compared to most other modal like settings - it would be nice for a smaller minimum window size (though this might require some rearranging).

There is also this small overlap I noticed on this tab:
![image](https://user-images.githubusercontent.com/54308792/128559267-45eb984d-052b-4702-930f-bb0ab7337bf4.png)

Fedora 34, Gnome 40

**Comment by amezin** [comment]
Fixed in v22
