### ISSUE TITLE
Shortcuts to change transparency not redrawing

### ISSUE THREAD

**Issue by jacksongoode** [amezin/gnome-shell-extension-ddterm#73]
Because there is a catch [here](https://github.com/amezin/gnome-shell-extension-ddterm/blob/988a5d988ad0bbee24dbeb7690e1348f7b935987/appwindow.js#L261) the window will not redraw/refresh if it begins its changes when `background-opacity === 1.0`. 

https://user-images.githubusercontent.com/54308792/128953115-c57afa44-62bc-434d-8c02-c7b1e74c764e.mp4

What I'm doing here is typing at 0% opacity, increasing it to 100%, toggling the window, reducing the opacity via shortcut to 0%, and then typing. The effects refresh if I change the window size (via shortcut here).

**Comment by amezin** [comment]
From https://github.com/amezin/gnome-shell-extension-ddterm/pull/72#discussion_r686318389

> I tried to record this via desktop but it looks like proper behavior there so I recorded externally.

Could you elaborate? You can't reproduce the bug if you enable recording, or the bug isn't visible in the record but still visible on screen?

Also:
Is it Xorg/Wayland/XWayland?
Which GNOME Shell version?

**Comment by jacksongoode** [comment]
Yes, Wayland for me GNOME 40.

I've found that this will fix the behavior for a session once the bug happens one time. Really weird because once it happens it works for future toggles.
```
this.simple_action('background-opacity-dec', () => {
    const paint = this.settings.get_double('background-opacity') === 1.0;
    this.adjust_double_setting('background-opacity', -OPACITY_MOD);
    if (paint) {
        if (this.draw_handler_id === null)
            this.draw_handler_id = this.connect('draw', this.draw.bind(this));
    }
});
```

**Comment by amezin** [comment]
It's almost the same as removing `this.settings.get_double('background-opacity') < 1.0;` from `update_app_paintable()`.
Except that in this case, the window will be effectively painted twice if `background-opacity` == `1.0`

> You can't reproduce the bug if you enable recording, or the bug isn't visible in the record but still visible on screen?

**Comment by jacksongoode** [comment]
Well, I'm not so sure if it's happening twice. I think the issue is that that condition `this.settings.get_double('background-opacity') < 1.0` is not met for some reason after the `adjust_double_setting`, otherwise it wouldn't need to be set again.

> You can't reproduce the bug if you enable recording, or the bug isn't visible in the record but still visible on screen?

https://user-images.githubusercontent.com/54308792/128976381-b12ede96-9aa8-4321-ab9e-8e64568ccf50.mp4

Actually, there is a bug on record. Not sure what to make of this... My background is black so turning the transparency down might be cutting directly through the applications under the window?

**Comment by amezin** [comment]
Maybe I don't understand you correctly, but I can't reproduce the issue.

> To be clear, this is not what a user sees, a user just sees the background remain the same color and the text becomes garbled.

If screen capture doesn't match the actual picture on the screen, this is likely a graphics driver/Wayland compositor (GNOME Shell) bug.

**Comment by amezin** [comment]
Please try the current `master` branch (commit 7976c0cfbdecb5e26d1adb08fd2c03649f63af2d)

**Comment by jacksongoode** [comment]
> Please try the current `master` branch (commit [7976c0c](https://github.com/amezin/gnome-shell-extension-ddterm/commit/7976c0cfbdecb5e26d1adb08fd2c03649f63af2d))

Unfortunately, the issue still exists. It only exists on the first load of ddterm.

**Comment by amezin** [comment]
After thinking a bit more... I think I'll accept a PR that removes `background-opacity < 1.0` condition from `update_app_paintable`. After all, there's already a checkbox that disables transparency.

By the way, could you reproduce the issue using only "Enable/Disable Background Transparency" shortcut?

**Comment by amezin** [comment]
@jacksongoode Please test the current `master` branch (e32db07c8e48803e22476249e667ef95ac52666b)

And, again, please try to reproduce the issue using "Enable/Disable Background Transparency" keyboard shortcut

**Comment by jacksongoode** [comment]
> @jacksongoode Please test the current `master` branch ([e32db07](https://github.com/amezin/gnome-shell-extension-ddterm/commit/e32db07c8e48803e22476249e667ef95ac52666b))
> 
> And, again, please try to reproduce the issue using "Enable/Disable Background Transparency" keyboard shortcut

Yes, while the bug doesn't exist anymore for the initial transparency change when background transparency is enabled, the bug will reappear if the background transparency is:

1. Toggled off
2. Toggled on
3. Change transparency with shortcut

**Comment by jacksongoode** [comment]
I believe this can be closed as it seems resolved.
