### ISSUE TITLE
Run tests on Fedora 35

### ISSUE THREAD

**Issue by amezin** [amezin/gnome-shell-extension-ddterm#85]
Current fedora:35 image is the same as fedora:rawhide, updated 2 months ago. Need to wait until there is a proper fedora:35 image

Attempts to use current fedora:35/rawhide as a base image fail with:

```
Error: Error downloading packages:
  Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=rawhide&arch=x86_64 [getaddrinfo() thread failed to start]
```

**Comment by jacksongoode** [comment]
I'm currently testing 21 on 35 beta. I'll let you know if there are any obvious issues.

**Comment by amezin** [comment]
@jacksongoode Thank you.

Although this task is about running automated tests (CI) :)

**Comment by amezin** [comment]
WRT `getaddrinfo() thread failed to start` I guess I'm hitting https://github.com/moby/moby/issues/42680

It seems that there's no release including the fix yet https://github.com/moby/moby/commit/9f6b562dd12ef7b1f9e2f8e6f2ab6477790a6594.

**Comment by amezin** [comment]
Buildkit 0.9.1 includes a fix https://github.com/moby/buildkit/pull/2379
It was enough to build the images on Github Actions.
