### ISSUE TITLE
Highlight Glitch When Searching

### ISSUE THREAD

**Issue by lfom** [amezin/gnome-shell-extension-ddterm#89]
Hello!

Thanks for ddterm, I have been using since a while ago and I really enjoy it. The search feature added in the latest release is really nice. One minor issue is that when the last (first) item is highlighted the find next (previous) key is pressed the highlight is hidden, what is a bit weird in my opinion, I do not remember seeing this behavior anywhere else.

Regards

**Comment by amezin** [comment]
Search is implemented mostly in the VTE library (the library used by GNOME Terminal, Guake, and many other Gtk terminals). I have almost no control over what it does.

Could you check whether the search in GNOME Terminal behaves the same way (for me it is)?

**Comment by lfom** [comment]
Yeah, it seems to do basically the same with "wrap" disabled (I enable it by default, that is why I did not notice it before). So I guess it is a VTE thingy.
